config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :drive_sessions, :only => [:index]
    end
  end
 
  resources :drive_sessions, :only => [:index]
  resources :dots, :only => [:index]
  get '/auth/tiber/callback' => 'sessions#create'
  get '/auth/failure' => 'welcome#failure'
  delete 'signout' => 'sessions#destroy', as: :signout 
  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/drive_session.rb
class DriveSession < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  class << self
    def from_omniauth(auth)
      Rails.logger.info "---> USER 1: #{auth.inspect}"
      where(provider: auth.provider, uid: auth.uid).first || create_from_omniauth(auth)
      #User.first
    end
    def create_from_omniauth(auth)
      create! do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
      end
    end
  end
end

app/controllers/api/v1/drive_sessions_controller.rb
module Api
  module V1
    class DriveSessionsController < ApplicationController
      respond_to :json

      def index
        respond_with DriveSession.all
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from OAuth2::Error do |exception|
    if exception.response.status == 401
      session[:user_id] = nil
      session[:access_token] = nil
      redirect_to root_url, alert: "Access token expired, try signing in again."
    end
  end

private
  def oauth_client
    @oauth_client ||= OAuth2::Client.new(ENV["TIBER_KEY"], 
      ENV["TIBER_SECRET"], site: ENV["TIBER_URL"])
  end

  def access_token
    if session[:access_token]
      @access_token ||= OAuth2::AccessToken.new(oauth_client, session[:access_token])
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/dots_controller.rb
class DotsController < ApplicationController
  layout 'application'

  def index
    @oc = oauth_client
    @at = access_token
    @dots = access_token.get("/api/v1/dots").parsed if access_token 
    # @dots = @json.map{|dot| JSON.parse(dot) }
  end

end

app/controllers/drive_sessions_controller.rb
class DriveSessionsController < ApplicationController
  layout 'application'

  def index
    @dss = DriveSession.all.to_a
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(auth_hash)
    session[:user_id] = user.id
    session[:access_token] = auth_hash["credentials"]["token"]
    #self.current_user = @user
    redirect_to dots_url, notice: "Signed in."
  end

  def destroy
    session[:user_id] = nil
    #session[:access_token] = nil
    redirect_to root_url, notice: "Signed out."
  end

  #protected
  private

  def auth_hash
    # Rails.logger.info "---> sc 1: #{request.env['omniauth.auth']}"
    request.env['omniauth.auth']
  end
  #def permitted_auth_hash
  #  x = auth_hash.permit('provider', 'id', info_attributes: ['email'])
  #  Rails.logger.info "---> sc 2: #{x.inspect}" 
  #  x
  #end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'application'

  def index
  end
  def failure
    @params = params
  end
  def callback
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dots/index.html.haml
%h3 Dots 

- unless @dots.nil?
  %table
    %thead
      %tr
        %th Rig 
        %th Firstname
        %th Lastname
        %th Created
    %tbody
      - @dots.each do |d|
        %tr
          %td= d['rig_id'].to_s
          %td= d['driver_firstname'].to_s
          %td= d['driver_lastname'].to_s
          %td= d['timestamp'].to_s
  

app/views/drive_sessions/index.html.haml
%h3 Drive Sessions
%table
  %thead
    %tr
      %th DS
      %th Rigid
      %th DU
      %th Cap Ct
      %th Updated
      %th Start
      %th End 
  %tbody 
    - @dss.each do |ds|
      %tr
        %td= ds.name
        %td= ds.rig_id
        %td= ds.du_id
        %td= ds.capture_count
        %td= ds.last_updated
        %td= ds.start_time
        %td= ds.end_time
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MWA | 
    <%= params[:action] %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/menu' %>
<%= yield %>

</body>
</html>

app/views/shared/_menu.html.haml
= link_to 'Home', root_path
|
= link_to 'Drive Sessions', drive_sessions_path 
|
= link_to 'Drive Sessions API', api_v1_drive_sessions_path 
|
= link_to 'Dots', dots_path 
|

- if current_user 
  Signed in as 
  = current_user.email 
  = link_to 'Sign Out', signout_path, :method => :delete
- else
  = link_to 'Sign In Thru Tiber', '/auth/tiber' 

- unless notice.blank?
  %p.notice= notice
- unless alert.blank?
  %p.alert= alert

app/views/welcome/callback.html.haml
%h3 Plain callback 
- # = @params.each_pair { |k, v| puts "#{k}: #{v}" }

app/views/welcome/failure.html.haml
%h3 Failed to authenticate.
= @params.each_pair { |k, v| puts "#{k}: #{v}" }

app/views/welcome/index.html.haml
%h3 Welcome.
%canvas#webglcanvas{:height => "500", :style => "border: none;", :width => "500"}